# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15da8030cdf0ea02ee73f9966acd74a12da5e5049cff5a1ee1d8b59f85d6182bc7a6c0f7942d62b0d85dc114e7d1f5c6a07a0ea6cb65ac4c5638d341e15596bb

test:
  secret_key_base: 43b9f2f324a514a05f41d0ad644893b60e9c1999ad251c1954038f6071e6dbb477814a173e66060b7250daa11a3b13c4bfadf67aac00c0a46ea18c00f5525b5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
